"""Initial migration

Revision ID: bb191ea484b1
Revises: 
Create Date: 2024-08-30 17:36:33.268655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb191ea484b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SYONLINE',
    sa.Column('ID', sa.String(length=36), nullable=False),
    sa.Column('CREATEDATETIME', sa.DateTime(), nullable=True),
    sa.Column('LOGINNAME', sa.String(length=100), nullable=True),
    sa.Column('IP', sa.String(length=100), nullable=True),
    sa.Column('TYPE', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_SYONLINE_CREATEDATETIME'), 'SYONLINE', ['CREATEDATETIME'], unique=False)
    op.create_table('SYORGANIZATION',
    sa.Column('ID', sa.String(length=36), nullable=False),
    sa.Column('CREATEDATETIME', sa.DateTime(), nullable=True),
    sa.Column('UPDATEDATETIME', sa.DateTime(), nullable=True),
    sa.Column('NAME', sa.String(length=200), nullable=True),
    sa.Column('ADDRESS', sa.String(length=200), nullable=True),
    sa.Column('CODE', sa.String(length=200), nullable=True),
    sa.Column('ICONCLS', sa.String(length=100), nullable=True),
    sa.Column('SEQ', sa.Integer(), nullable=True),
    sa.Column('LEADER', sa.String(length=20), nullable=True),
    sa.Column('PHONE', sa.String(length=11), nullable=True),
    sa.Column('EMAIL', sa.String(length=50), nullable=True),
    sa.Column('STATUS', sa.String(length=10), nullable=True),
    sa.Column('SYORGANIZATION_ID', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['SYORGANIZATION_ID'], ['SYORGANIZATION.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_SYORGANIZATION_CREATEDATETIME'), 'SYORGANIZATION', ['CREATEDATETIME'], unique=False)
    op.create_index(op.f('ix_SYORGANIZATION_UPDATEDATETIME'), 'SYORGANIZATION', ['UPDATEDATETIME'], unique=False)
    op.create_table('SYRESOURCETYPE',
    sa.Column('ID', sa.String(length=36), nullable=False),
    sa.Column('CREATEDATETIME', sa.DateTime(), nullable=True),
    sa.Column('UPDATEDATETIME', sa.DateTime(), nullable=True),
    sa.Column('NAME', sa.String(length=100), nullable=True),
    sa.Column('DESCRIPTION', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_SYRESOURCETYPE_CREATEDATETIME'), 'SYRESOURCETYPE', ['CREATEDATETIME'], unique=False)
    op.create_index(op.f('ix_SYRESOURCETYPE_UPDATEDATETIME'), 'SYRESOURCETYPE', ['UPDATEDATETIME'], unique=False)
    op.create_table('SYROLE',
    sa.Column('ID', sa.String(length=32), nullable=False),
    sa.Column('CREATEDATETIME', sa.DateTime(), nullable=True),
    sa.Column('UPDATEDATETIME', sa.DateTime(), nullable=True),
    sa.Column('NAME', sa.String(length=100), nullable=True),
    sa.Column('DESCRIPTION', sa.String(length=200), nullable=True),
    sa.Column('ICONCLS', sa.String(length=100), nullable=True),
    sa.Column('SEQ', sa.Integer(), nullable=True),
    sa.Column('ROLEKEY', sa.String(length=100), nullable=True),
    sa.Column('DATASCOPE', sa.Integer(), nullable=True),
    sa.Column('STATUS', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_SYROLE_CREATEDATETIME'), 'SYROLE', ['CREATEDATETIME'], unique=False)
    op.create_index(op.f('ix_SYROLE_UPDATEDATETIME'), 'SYROLE', ['UPDATEDATETIME'], unique=False)
    op.create_table('SYS_CONFIG',
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('config_name', sa.String(length=100), nullable=True),
    sa.Column('config_key', sa.String(length=100), nullable=True),
    sa.Column('config_value', sa.String(length=500), nullable=True),
    sa.Column('config_type', sa.Integer(), nullable=True),
    sa.Column('create_by', sa.String(length=64), nullable=True),
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_by', sa.String(length=64), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.Column('remark', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('config_id')
    )
    op.create_table('SYS_DICT_TYPE',
    sa.Column('dict_id', sa.Integer(), nullable=False),
    sa.Column('dict_name', sa.String(length=100), nullable=True),
    sa.Column('dict_type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('create_by', sa.String(length=64), nullable=True),
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_by', sa.String(length=64), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.Column('remark', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('dict_id'),
    sa.UniqueConstraint('dict_type')
    )
    op.create_table('SYUSER',
    sa.Column('ID', sa.String(length=36), nullable=False),
    sa.Column('CREATEDATETIME', sa.DateTime(), nullable=True),
    sa.Column('UPDATEDATETIME', sa.DateTime(), nullable=True),
    sa.Column('LOGINNAME', sa.String(length=100), nullable=True),
    sa.Column('PWD', sa.String(length=100), nullable=True),
    sa.Column('NAME', sa.String(length=100), nullable=True),
    sa.Column('SEX', sa.String(length=1), nullable=True),
    sa.Column('AGE', sa.Integer(), nullable=True),
    sa.Column('PHOTO', sa.String(length=200), nullable=True),
    sa.Column('EMPLOYDATE', sa.DATETIME(), nullable=True),
    sa.Column('EMAIL', sa.String(length=50), nullable=True),
    sa.Column('PHONENUMBER', sa.String(length=11), nullable=True),
    sa.Column('STATUS', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_SYUSER_CREATEDATETIME'), 'SYUSER', ['CREATEDATETIME'], unique=False)
    op.create_index(op.f('ix_SYUSER_LOGINNAME'), 'SYUSER', ['LOGINNAME'], unique=True)
    op.create_index(op.f('ix_SYUSER_UPDATEDATETIME'), 'SYUSER', ['UPDATEDATETIME'], unique=False)
    op.create_table('datasets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('data_description', sa.Text(), nullable=False),
    sa.Column('path', sa.String(length=100), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.Column('created_username', sa.String(length=100), nullable=False),
    sa.Column('created_userrole', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('netcat',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('preprocess',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('create_username', sa.String(length=100), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('preprocess_method',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('path', sa.String(length=100), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('created_username', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('SYRESOURCE',
    sa.Column('ID', sa.String(length=36), nullable=False),
    sa.Column('CREATEDATETIME', sa.DateTime(), nullable=True),
    sa.Column('DESCRIPTION', sa.String(length=200), nullable=True),
    sa.Column('ICONCLS', sa.String(length=100), nullable=True),
    sa.Column('NAME', sa.String(length=100), nullable=True),
    sa.Column('SEQ', sa.Integer(), nullable=True),
    sa.Column('TARGET', sa.String(length=100), nullable=True),
    sa.Column('UPDATEDATETIME', sa.DateTime(), nullable=True),
    sa.Column('PATH', sa.String(length=200), nullable=True),
    sa.Column('URL', sa.String(length=200), nullable=True),
    sa.Column('PERMS', sa.String(length=150), nullable=True),
    sa.Column('SYRESOURCE_ID', sa.String(length=32), nullable=True),
    sa.Column('SYRESOURCETYPE_ID', sa.String(length=32), nullable=True),
    sa.Column('STATUS', sa.String(length=10), nullable=True),
    sa.Column('IS_CACHE', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['SYRESOURCETYPE_ID'], ['SYRESOURCETYPE.ID'], ),
    sa.ForeignKeyConstraint(['SYRESOURCE_ID'], ['SYRESOURCE.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_SYRESOURCE_CREATEDATETIME'), 'SYRESOURCE', ['CREATEDATETIME'], unique=False)
    op.create_index(op.f('ix_SYRESOURCE_UPDATEDATETIME'), 'SYRESOURCE', ['UPDATEDATETIME'], unique=False)
    op.create_table('SYROLE_SYORGANIZATION',
    sa.Column('SYROLE_ID', sa.String(length=32), nullable=True),
    sa.Column('SYORGANIZATION_ID', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['SYORGANIZATION_ID'], ['SYORGANIZATION.ID'], ),
    sa.ForeignKeyConstraint(['SYROLE_ID'], ['SYROLE.ID'], )
    )
    op.create_table('SYS_DICT_DATA',
    sa.Column('dict_code', sa.Integer(), nullable=False),
    sa.Column('dict_sort', sa.Integer(), nullable=True),
    sa.Column('dict_label', sa.String(length=100), nullable=True),
    sa.Column('dict_value', sa.String(length=100), nullable=True),
    sa.Column('dict_type', sa.String(length=100), nullable=True),
    sa.Column('css_class', sa.String(length=100), nullable=True),
    sa.Column('list_class', sa.String(length=100), nullable=True),
    sa.Column('is_default', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('create_by', sa.String(length=64), nullable=True),
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_by', sa.String(length=64), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.Column('remark', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['dict_type'], ['SYS_DICT_TYPE.dict_type'], ),
    sa.PrimaryKeyConstraint('dict_code')
    )
    op.create_table('SYUSER_SYORGANIZATION',
    sa.Column('SYUSER_ID', sa.String(length=36), nullable=True),
    sa.Column('SYORGANIZATION_ID', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['SYORGANIZATION_ID'], ['SYORGANIZATION.ID'], ),
    sa.ForeignKeyConstraint(['SYUSER_ID'], ['SYUSER.ID'], )
    )
    op.create_table('SYUSER_SYROLE',
    sa.Column('SYUSER_ID', sa.String(length=36), nullable=True),
    sa.Column('SYROLE_ID', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['SYROLE_ID'], ['SYROLE.ID'], ),
    sa.ForeignKeyConstraint(['SYUSER_ID'], ['SYUSER.ID'], )
    )
    op.create_table('network',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('network_params', sa.String(length=500), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('is_deep', sa.Integer(), nullable=True),
    sa.Column('created_username', sa.String(length=100), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['netcat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('testdata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('input', sa.String(length=255), nullable=False),
    sa.Column('output', sa.String(length=255), nullable=False),
    sa.Column('origin_dataset', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('created_username', sa.String(length=100), nullable=False),
    sa.Column('created_userrole', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['origin_dataset'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('SYORGANIZATION_SYRESOURCE',
    sa.Column('SYRESOURCE_ID', sa.String(length=32), nullable=True),
    sa.Column('SYORGANIZATION_ID', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['SYORGANIZATION_ID'], ['SYORGANIZATION.ID'], ),
    sa.ForeignKeyConstraint(['SYRESOURCE_ID'], ['SYRESOURCE.ID'], )
    )
    op.create_table('SYROLE_SYRESOURCE',
    sa.Column('SYROLE_ID', sa.String(length=32), nullable=True),
    sa.Column('SYRESOURCE_ID', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['SYRESOURCE_ID'], ['SYRESOURCE.ID'], ),
    sa.ForeignKeyConstraint(['SYROLE_ID'], ['SYROLE.ID'], )
    )
    op.create_table('model_application',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_description', sa.Text(), nullable=False),
    sa.Column('data_id', sa.Integer(), nullable=False),
    sa.Column('params', sa.String(length=500), nullable=False),
    sa.Column('network_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('created_username', sa.String(length=100), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['data_id'], ['testdata.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['network_id'], ['network.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('preprocessed_dataset',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('data_description', sa.String(length=500), nullable=False),
    sa.Column('path', sa.String(length=100), nullable=False),
    sa.Column('testdata_id', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('created_username', sa.String(length=100), nullable=False),
    sa.Column('preprocess_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['preprocess_id'], ['preprocess_method.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['testdata_id'], ['testdata.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appparams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('params', sa.String(length=500), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.Column('model_path', sa.String(length=255), nullable=True),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('train_time', sa.DateTime(), nullable=True),
    sa.Column('test_image', sa.String(length=255), nullable=True),
    sa.Column('eva', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['model_application.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rankings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('testdata_id', sa.Integer(), nullable=False),
    sa.Column('apparams_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['apparams_id'], ['appparams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['testdata_id'], ['testdata.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rankings')
    op.drop_table('appparams')
    op.drop_table('preprocessed_dataset')
    op.drop_table('model_application')
    op.drop_table('SYROLE_SYRESOURCE')
    op.drop_table('SYORGANIZATION_SYRESOURCE')
    op.drop_table('testdata')
    op.drop_table('network')
    op.drop_table('SYUSER_SYROLE')
    op.drop_table('SYUSER_SYORGANIZATION')
    op.drop_table('SYS_DICT_DATA')
    op.drop_table('SYROLE_SYORGANIZATION')
    op.drop_index(op.f('ix_SYRESOURCE_UPDATEDATETIME'), table_name='SYRESOURCE')
    op.drop_index(op.f('ix_SYRESOURCE_CREATEDATETIME'), table_name='SYRESOURCE')
    op.drop_table('SYRESOURCE')
    op.drop_table('preprocess_method')
    op.drop_table('preprocess')
    op.drop_table('netcat')
    op.drop_table('datasets')
    op.drop_index(op.f('ix_SYUSER_UPDATEDATETIME'), table_name='SYUSER')
    op.drop_index(op.f('ix_SYUSER_LOGINNAME'), table_name='SYUSER')
    op.drop_index(op.f('ix_SYUSER_CREATEDATETIME'), table_name='SYUSER')
    op.drop_table('SYUSER')
    op.drop_table('SYS_DICT_TYPE')
    op.drop_table('SYS_CONFIG')
    op.drop_index(op.f('ix_SYROLE_UPDATEDATETIME'), table_name='SYROLE')
    op.drop_index(op.f('ix_SYROLE_CREATEDATETIME'), table_name='SYROLE')
    op.drop_table('SYROLE')
    op.drop_index(op.f('ix_SYRESOURCETYPE_UPDATEDATETIME'), table_name='SYRESOURCETYPE')
    op.drop_index(op.f('ix_SYRESOURCETYPE_CREATEDATETIME'), table_name='SYRESOURCETYPE')
    op.drop_table('SYRESOURCETYPE')
    op.drop_index(op.f('ix_SYORGANIZATION_UPDATEDATETIME'), table_name='SYORGANIZATION')
    op.drop_index(op.f('ix_SYORGANIZATION_CREATEDATETIME'), table_name='SYORGANIZATION')
    op.drop_table('SYORGANIZATION')
    op.drop_index(op.f('ix_SYONLINE_CREATEDATETIME'), table_name='SYONLINE')
    op.drop_table('SYONLINE')
    # ### end Alembic commands ###
